permalink: /:year/:month/:day/:title.html
pygments: false
exclude:
  - pre-process.rb
author: al3xandr3
title: AL3XANDR3
keywords: programming, probabilities, machine learning, alexandre martins, al3xandr3
url: http://al3xandr3.github.com