permalink: /:year/:month/:day/:title.html
pygments: true
auto:     true
markdown: maruku
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
exclude:
  - pre-process.rb
author: al3xandr3
title: al3xandr3
keywords: programming, probabilities, machine learning, alexandre martins, al3xandr3
url: http://al3xandr3.github.com
paginate: 4