permalink: /:year/:month/:day/:title.html
author: al3xandr3
title: al3xandr3
keywords: programming, data, machine learning, alexandre martins, al3xandr3
url: http://al3xandr3.github.com
paginate: 6
pygments: false
markdown: redcarpet
redcarpet:
  extensions: ["tables","with_toc_data", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
